run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gocritic
    - gosec
    - misspell
    - gocyclo
    - whitespace

issues:
  exclude-use-default: false
