# .goreleaser.yaml
version: 2
project_name: refreSSH

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/refressh
    binary: refressh

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: desc
  format: "{{ .Message }}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: '🚀 Features'
      regexp: "^.*feat[(\\w)]*!?:.+$"
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: "^.*fix[(\\w)]*!?:.+$"
      order: 1
    - title: '🔒 Security'
      regexp: "^.*security[(\\w)]*!?:.+$"
      order: 2
    - title: '✨ Enhancements'
      regexp: "^.*perf[(\\w)]*!?:.+$"
      order: 3
    - title: '🛠 Refactoring'
      regexp: "^.*refactor[(\\w)]*!?:.+$"
      order: 4
    - title: '📝 Documentation'
      regexp: "^.*docs[(\\w)]*!?:.+$"
      order: 5
    - title: '🔄 CI/CD'
      regexp: "^.*ci[(\\w)]*!?:.+$"
      order: 6
    - title: '🧪 Testing'
      regexp: "^.*test[(\\w)]*!?:.+$"
      order: 7
    - title: '🧹 Others'
      order: 99
